name: Publish to VS Code Marketplace

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      pre_release:
        description: 'Publish as pre-release'
        required: false
        default: false
        type: boolean

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Lint code
        run: npm run lint

      - name: Compile TypeScript
        run: npm run compile

      - name: Package extension (release)
        if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && !inputs.pre_release)
        run: npm run package

      - name: Package extension (pre-release)
        if: github.event_name == 'workflow_dispatch' && inputs.pre_release
        run: npm run package:pre-release

      - name: Publish to marketplace (release)
        if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && !inputs.pre_release)
        run: npm run publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Publish to marketplace (pre-release)
        if: github.event_name == 'workflow_dispatch' && inputs.pre_release
        run: npm run publish:pre-release
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: howmany-vscode-${{ github.event.release.tag_name || 'latest' }}.vsix
          path: '*.vsix'
          retention-days: 30 